__title__ = 'botosts'
__description__ = 'This is a boto(2)/boto3 wrapper that handles STS Assume Role.'
__url__ = 'https://bitbucket.org/morea/boto-sts-assume-role/'
__version__ = '1.0'
__author__ = 'Claranet Public Cloud'
__author_email__ = 'jerome.respaut@fr.clara.net'
__license__ = 'Apache 2.0'
__copyright__ = 'Copyright 2018 Claranet'
